//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG.ContratacionWeb.Pyme.ServicioToken {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenObtiene", Namespace="http://schemas.datacontract.org/2004/07/BG.WCF.TokenService.Data")]
    [System.SerializableAttribute()]
    public partial class TokenObtiene : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BG.ContratacionWeb.Pyme.ServicioToken.dataObtiene dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BG.ContratacionWeb.Pyme.ServicioToken.meta metaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BG.ContratacionWeb.Pyme.ServicioToken.dataObtiene data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BG.ContratacionWeb.Pyme.ServicioToken.meta meta {
            get {
                return this.metaField;
            }
            set {
                if ((object.ReferenceEquals(this.metaField, value) != true)) {
                    this.metaField = value;
                    this.RaisePropertyChanged("meta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dataObtiene", Namespace="http://schemas.datacontract.org/2004/07/BG.WCF.TokenService.Data")]
    [System.SerializableAttribute()]
    public partial class dataObtiene : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="meta", Namespace="http://schemas.datacontract.org/2004/07/BG.WCF.TokenService.Data")]
    [System.SerializableAttribute()]
    public partial class meta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool collectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int countField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool collection {
            get {
                return this.collectionField;
            }
            set {
                if ((this.collectionField.Equals(value) != true)) {
                    this.collectionField = value;
                    this.RaisePropertyChanged("collection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                if ((this.countField.Equals(value) != true)) {
                    this.countField = value;
                    this.RaisePropertyChanged("count");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenValida", Namespace="http://schemas.datacontract.org/2004/07/BG.WCF.TokenService.Data")]
    [System.SerializableAttribute()]
    public partial class TokenValida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BG.ContratacionWeb.Pyme.ServicioToken.dataValida dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BG.ContratacionWeb.Pyme.ServicioToken.meta metaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BG.ContratacionWeb.Pyme.ServicioToken.dataValida data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BG.ContratacionWeb.Pyme.ServicioToken.meta meta {
            get {
                return this.metaField;
            }
            set {
                if ((object.ReferenceEquals(this.metaField, value) != true)) {
                    this.metaField = value;
                    this.RaisePropertyChanged("meta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dataValida", Namespace="http://schemas.datacontract.org/2004/07/BG.WCF.TokenService.Data")]
    [System.SerializableAttribute()]
    public partial class dataValida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aplicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string canalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string metajsonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.aplicacionField, value) != true)) {
                    this.aplicacionField = value;
                    this.RaisePropertyChanged("aplicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                if ((object.ReferenceEquals(this.canalField, value) != true)) {
                    this.canalField = value;
                    this.RaisePropertyChanged("canal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string metajson {
            get {
                return this.metajsonField;
            }
            set {
                if ((object.ReferenceEquals(this.metajsonField, value) != true)) {
                    this.metajsonField = value;
                    this.RaisePropertyChanged("metajson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioToken.ITokenService")]
    public interface ITokenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenService/GenerarToken", ReplyAction="http://tempuri.org/ITokenService/GenerarTokenResponse")]
        BG.ContratacionWeb.Pyme.ServicioToken.TokenObtiene GenerarToken(string canal, string aplicacion, string metajson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenService/GenerarToken", ReplyAction="http://tempuri.org/ITokenService/GenerarTokenResponse")]
        System.Threading.Tasks.Task<BG.ContratacionWeb.Pyme.ServicioToken.TokenObtiene> GenerarTokenAsync(string canal, string aplicacion, string metajson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenService/RecuperarInfToken", ReplyAction="http://tempuri.org/ITokenService/RecuperarInfTokenResponse")]
        BG.ContratacionWeb.Pyme.ServicioToken.TokenValida RecuperarInfToken(string token, string canal, string aplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenService/RecuperarInfToken", ReplyAction="http://tempuri.org/ITokenService/RecuperarInfTokenResponse")]
        System.Threading.Tasks.Task<BG.ContratacionWeb.Pyme.ServicioToken.TokenValida> RecuperarInfTokenAsync(string token, string canal, string aplicacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITokenServiceChannel : BG.ContratacionWeb.Pyme.ServicioToken.ITokenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenServiceClient : System.ServiceModel.ClientBase<BG.ContratacionWeb.Pyme.ServicioToken.ITokenService>, BG.ContratacionWeb.Pyme.ServicioToken.ITokenService {
        
        public TokenServiceClient() {
        }
        
        public TokenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BG.ContratacionWeb.Pyme.ServicioToken.TokenObtiene GenerarToken(string canal, string aplicacion, string metajson) {
            return base.Channel.GenerarToken(canal, aplicacion, metajson);
        }
        
        public System.Threading.Tasks.Task<BG.ContratacionWeb.Pyme.ServicioToken.TokenObtiene> GenerarTokenAsync(string canal, string aplicacion, string metajson) {
            return base.Channel.GenerarTokenAsync(canal, aplicacion, metajson);
        }
        
        public BG.ContratacionWeb.Pyme.ServicioToken.TokenValida RecuperarInfToken(string token, string canal, string aplicacion) {
            return base.Channel.RecuperarInfToken(token, canal, aplicacion);
        }
        
        public System.Threading.Tasks.Task<BG.ContratacionWeb.Pyme.ServicioToken.TokenValida> RecuperarInfTokenAsync(string token, string canal, string aplicacion) {
            return base.Channel.RecuperarInfTokenAsync(token, canal, aplicacion);
        }
    }
}
