//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BG.ContratacionWeb.Pyme.ServicioRatingEmpresarial {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsConsultaExternaSoap", Namespace="http://tempuri.org/")]
    public partial class wsConsultaExterna : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarPrecalificadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcesarPDFImpuestoRentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcesarPDFDeclaracionIVAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcesoDeclaracionIVAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaAnyosWebOperationCompleted;
        
        private System.Threading.SendOrPostCallback Consultar_Ins_Updt_Clientes_Rating_NeoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarVariaciones_Indicadores_FlujoEfectivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarAnalisisCualitativoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarCalificacionSBSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaHostGarantiasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaMesesIvaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaHostRiesgosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsConsultaExterna() {
            this.Url = global::BG.ContratacionWeb.Pyme.Properties.Settings.Default.BG_ContratacionWeb_Pyme_ServicioRatingEmpresarial_wsConsultaExterna;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarPrecalificadorCompletedEventHandler ConsultarPrecalificadorCompleted;
        
        /// <remarks/>
        public event ProcesarPDFImpuestoRentaCompletedEventHandler ProcesarPDFImpuestoRentaCompleted;
        
        /// <remarks/>
        public event ProcesarPDFDeclaracionIVACompletedEventHandler ProcesarPDFDeclaracionIVACompleted;
        
        /// <remarks/>
        public event ProcesoDeclaracionIVACompletedEventHandler ProcesoDeclaracionIVACompleted;
        
        /// <remarks/>
        public event ConsultaAnyosWebCompletedEventHandler ConsultaAnyosWebCompleted;
        
        /// <remarks/>
        public event Consultar_Ins_Updt_Clientes_Rating_NeoCompletedEventHandler Consultar_Ins_Updt_Clientes_Rating_NeoCompleted;
        
        /// <remarks/>
        public event GenerarVariaciones_Indicadores_FlujoEfectivoCompletedEventHandler GenerarVariaciones_Indicadores_FlujoEfectivoCompleted;
        
        /// <remarks/>
        public event GenerarAnalisisCualitativoCompletedEventHandler GenerarAnalisisCualitativoCompleted;
        
        /// <remarks/>
        public event GenerarCalificacionSBSCompletedEventHandler GenerarCalificacionSBSCompleted;
        
        /// <remarks/>
        public event ConsultaHostGarantiasCompletedEventHandler ConsultaHostGarantiasCompleted;
        
        /// <remarks/>
        public event ConsultaMesesIvaCompletedEventHandler ConsultaMesesIvaCompleted;
        
        /// <remarks/>
        public event ConsultaHostRiesgosCompletedEventHandler ConsultaHostRiesgosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarPrecalificador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultarPrecalificador(string numeroIdentificacion) {
            object[] results = this.Invoke("ConsultarPrecalificador", new object[] {
                        numeroIdentificacion});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPrecalificadorAsync(string numeroIdentificacion) {
            this.ConsultarPrecalificadorAsync(numeroIdentificacion, null);
        }
        
        /// <remarks/>
        public void ConsultarPrecalificadorAsync(string numeroIdentificacion, object userState) {
            if ((this.ConsultarPrecalificadorOperationCompleted == null)) {
                this.ConsultarPrecalificadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPrecalificadorOperationCompleted);
            }
            this.InvokeAsync("ConsultarPrecalificador", new object[] {
                        numeroIdentificacion}, this.ConsultarPrecalificadorOperationCompleted, userState);
        }
        
        private void OnConsultarPrecalificadorOperationCompleted(object arg) {
            if ((this.ConsultarPrecalificadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPrecalificadorCompleted(this, new ConsultarPrecalificadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcesarPDFImpuestoRenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ProcesarPDFImpuestoRenta(string numIdentificacion, string anyo, string file, string idProceso, string fechaEstado, string usuario, ref string codError, ref string mensajeRetorno) {
            object[] results = this.Invoke("ProcesarPDFImpuestoRenta", new object[] {
                        numIdentificacion,
                        anyo,
                        file,
                        idProceso,
                        fechaEstado,
                        usuario,
                        codError,
                        mensajeRetorno});
            codError = ((string)(results[1]));
            mensajeRetorno = ((string)(results[2]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ProcesarPDFImpuestoRentaAsync(string numIdentificacion, string anyo, string file, string idProceso, string fechaEstado, string usuario, string codError, string mensajeRetorno) {
            this.ProcesarPDFImpuestoRentaAsync(numIdentificacion, anyo, file, idProceso, fechaEstado, usuario, codError, mensajeRetorno, null);
        }
        
        /// <remarks/>
        public void ProcesarPDFImpuestoRentaAsync(string numIdentificacion, string anyo, string file, string idProceso, string fechaEstado, string usuario, string codError, string mensajeRetorno, object userState) {
            if ((this.ProcesarPDFImpuestoRentaOperationCompleted == null)) {
                this.ProcesarPDFImpuestoRentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesarPDFImpuestoRentaOperationCompleted);
            }
            this.InvokeAsync("ProcesarPDFImpuestoRenta", new object[] {
                        numIdentificacion,
                        anyo,
                        file,
                        idProceso,
                        fechaEstado,
                        usuario,
                        codError,
                        mensajeRetorno}, this.ProcesarPDFImpuestoRentaOperationCompleted, userState);
        }
        
        private void OnProcesarPDFImpuestoRentaOperationCompleted(object arg) {
            if ((this.ProcesarPDFImpuestoRentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesarPDFImpuestoRentaCompleted(this, new ProcesarPDFImpuestoRentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcesarPDFDeclaracionIVA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProcesarPDFDeclaracionIVA(string numIdentificacion, string mes, string file, string fecha, ref string codError, ref string mensajeRetorno) {
            object[] results = this.Invoke("ProcesarPDFDeclaracionIVA", new object[] {
                        numIdentificacion,
                        mes,
                        file,
                        fecha,
                        codError,
                        mensajeRetorno});
            codError = ((string)(results[1]));
            mensajeRetorno = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProcesarPDFDeclaracionIVAAsync(string numIdentificacion, string mes, string file, string fecha, string codError, string mensajeRetorno) {
            this.ProcesarPDFDeclaracionIVAAsync(numIdentificacion, mes, file, fecha, codError, mensajeRetorno, null);
        }
        
        /// <remarks/>
        public void ProcesarPDFDeclaracionIVAAsync(string numIdentificacion, string mes, string file, string fecha, string codError, string mensajeRetorno, object userState) {
            if ((this.ProcesarPDFDeclaracionIVAOperationCompleted == null)) {
                this.ProcesarPDFDeclaracionIVAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesarPDFDeclaracionIVAOperationCompleted);
            }
            this.InvokeAsync("ProcesarPDFDeclaracionIVA", new object[] {
                        numIdentificacion,
                        mes,
                        file,
                        fecha,
                        codError,
                        mensajeRetorno}, this.ProcesarPDFDeclaracionIVAOperationCompleted, userState);
        }
        
        private void OnProcesarPDFDeclaracionIVAOperationCompleted(object arg) {
            if ((this.ProcesarPDFDeclaracionIVACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesarPDFDeclaracionIVACompleted(this, new ProcesarPDFDeclaracionIVACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcesoDeclaracionIVA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ProcesoDeclaracionIVA(string opcion, string idProceso, double mes1, double mes2, double mes3, ref string codError, ref string mensajeRetorno) {
            object[] results = this.Invoke("ProcesoDeclaracionIVA", new object[] {
                        opcion,
                        idProceso,
                        mes1,
                        mes2,
                        mes3,
                        codError,
                        mensajeRetorno});
            codError = ((string)(results[0]));
            mensajeRetorno = ((string)(results[1]));
        }
        
        /// <remarks/>
        public void ProcesoDeclaracionIVAAsync(string opcion, string idProceso, double mes1, double mes2, double mes3, string codError, string mensajeRetorno) {
            this.ProcesoDeclaracionIVAAsync(opcion, idProceso, mes1, mes2, mes3, codError, mensajeRetorno, null);
        }
        
        /// <remarks/>
        public void ProcesoDeclaracionIVAAsync(string opcion, string idProceso, double mes1, double mes2, double mes3, string codError, string mensajeRetorno, object userState) {
            if ((this.ProcesoDeclaracionIVAOperationCompleted == null)) {
                this.ProcesoDeclaracionIVAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesoDeclaracionIVAOperationCompleted);
            }
            this.InvokeAsync("ProcesoDeclaracionIVA", new object[] {
                        opcion,
                        idProceso,
                        mes1,
                        mes2,
                        mes3,
                        codError,
                        mensajeRetorno}, this.ProcesoDeclaracionIVAOperationCompleted, userState);
        }
        
        private void OnProcesoDeclaracionIVAOperationCompleted(object arg) {
            if ((this.ProcesoDeclaracionIVACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesoDeclaracionIVACompleted(this, new ProcesoDeclaracionIVACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaAnyosWeb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaAnyosWeb(string RUC, string fechaRevision, string idProceso) {
            object[] results = this.Invoke("ConsultaAnyosWeb", new object[] {
                        RUC,
                        fechaRevision,
                        idProceso});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaAnyosWebAsync(string RUC, string fechaRevision, string idProceso) {
            this.ConsultaAnyosWebAsync(RUC, fechaRevision, idProceso, null);
        }
        
        /// <remarks/>
        public void ConsultaAnyosWebAsync(string RUC, string fechaRevision, string idProceso, object userState) {
            if ((this.ConsultaAnyosWebOperationCompleted == null)) {
                this.ConsultaAnyosWebOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaAnyosWebOperationCompleted);
            }
            this.InvokeAsync("ConsultaAnyosWeb", new object[] {
                        RUC,
                        fechaRevision,
                        idProceso}, this.ConsultaAnyosWebOperationCompleted, userState);
        }
        
        private void OnConsultaAnyosWebOperationCompleted(object arg) {
            if ((this.ConsultaAnyosWebCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaAnyosWebCompleted(this, new ConsultaAnyosWebCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Consultar_Ins_Updt_Clientes_Rating_Neo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Consultar_Ins_Updt_Clientes_Rating_Neo(string RUC, string nombreCliente, string direccion, ref string CodError, ref string mensajeRetorno, ref string IdClienteRating, ref string IdProcesoRating, ref string fechaRevision) {
            object[] results = this.Invoke("Consultar_Ins_Updt_Clientes_Rating_Neo", new object[] {
                        RUC,
                        nombreCliente,
                        direccion,
                        CodError,
                        mensajeRetorno,
                        IdClienteRating,
                        IdProcesoRating,
                        fechaRevision});
            CodError = ((string)(results[0]));
            mensajeRetorno = ((string)(results[1]));
            IdClienteRating = ((string)(results[2]));
            IdProcesoRating = ((string)(results[3]));
            fechaRevision = ((string)(results[4]));
        }
        
        /// <remarks/>
        public void Consultar_Ins_Updt_Clientes_Rating_NeoAsync(string RUC, string nombreCliente, string direccion, string CodError, string mensajeRetorno, string IdClienteRating, string IdProcesoRating, string fechaRevision) {
            this.Consultar_Ins_Updt_Clientes_Rating_NeoAsync(RUC, nombreCliente, direccion, CodError, mensajeRetorno, IdClienteRating, IdProcesoRating, fechaRevision, null);
        }
        
        /// <remarks/>
        public void Consultar_Ins_Updt_Clientes_Rating_NeoAsync(string RUC, string nombreCliente, string direccion, string CodError, string mensajeRetorno, string IdClienteRating, string IdProcesoRating, string fechaRevision, object userState) {
            if ((this.Consultar_Ins_Updt_Clientes_Rating_NeoOperationCompleted == null)) {
                this.Consultar_Ins_Updt_Clientes_Rating_NeoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultar_Ins_Updt_Clientes_Rating_NeoOperationCompleted);
            }
            this.InvokeAsync("Consultar_Ins_Updt_Clientes_Rating_Neo", new object[] {
                        RUC,
                        nombreCliente,
                        direccion,
                        CodError,
                        mensajeRetorno,
                        IdClienteRating,
                        IdProcesoRating,
                        fechaRevision}, this.Consultar_Ins_Updt_Clientes_Rating_NeoOperationCompleted, userState);
        }
        
        private void OnConsultar_Ins_Updt_Clientes_Rating_NeoOperationCompleted(object arg) {
            if ((this.Consultar_Ins_Updt_Clientes_Rating_NeoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consultar_Ins_Updt_Clientes_Rating_NeoCompleted(this, new Consultar_Ins_Updt_Clientes_Rating_NeoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarVariaciones_Indicadores_FlujoEfectivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerarVariaciones_Indicadores_FlujoEfectivo(string idProceso, string usuario, ref string codError, ref string mensajeRetorno) {
            object[] results = this.Invoke("GenerarVariaciones_Indicadores_FlujoEfectivo", new object[] {
                        idProceso,
                        usuario,
                        codError,
                        mensajeRetorno});
            codError = ((string)(results[0]));
            mensajeRetorno = ((string)(results[1]));
        }
        
        /// <remarks/>
        public void GenerarVariaciones_Indicadores_FlujoEfectivoAsync(string idProceso, string usuario, string codError, string mensajeRetorno) {
            this.GenerarVariaciones_Indicadores_FlujoEfectivoAsync(idProceso, usuario, codError, mensajeRetorno, null);
        }
        
        /// <remarks/>
        public void GenerarVariaciones_Indicadores_FlujoEfectivoAsync(string idProceso, string usuario, string codError, string mensajeRetorno, object userState) {
            if ((this.GenerarVariaciones_Indicadores_FlujoEfectivoOperationCompleted == null)) {
                this.GenerarVariaciones_Indicadores_FlujoEfectivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarVariaciones_Indicadores_FlujoEfectivoOperationCompleted);
            }
            this.InvokeAsync("GenerarVariaciones_Indicadores_FlujoEfectivo", new object[] {
                        idProceso,
                        usuario,
                        codError,
                        mensajeRetorno}, this.GenerarVariaciones_Indicadores_FlujoEfectivoOperationCompleted, userState);
        }
        
        private void OnGenerarVariaciones_Indicadores_FlujoEfectivoOperationCompleted(object arg) {
            if ((this.GenerarVariaciones_Indicadores_FlujoEfectivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarVariaciones_Indicadores_FlujoEfectivoCompleted(this, new GenerarVariaciones_Indicadores_FlujoEfectivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarAnalisisCualitativo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerarAnalisisCualitativo(string idProceso, string idCliente, string fechaRevision, string usuario, ref string codError, ref string mensajeRetorno) {
            object[] results = this.Invoke("GenerarAnalisisCualitativo", new object[] {
                        idProceso,
                        idCliente,
                        fechaRevision,
                        usuario,
                        codError,
                        mensajeRetorno});
            codError = ((string)(results[0]));
            mensajeRetorno = ((string)(results[1]));
        }
        
        /// <remarks/>
        public void GenerarAnalisisCualitativoAsync(string idProceso, string idCliente, string fechaRevision, string usuario, string codError, string mensajeRetorno) {
            this.GenerarAnalisisCualitativoAsync(idProceso, idCliente, fechaRevision, usuario, codError, mensajeRetorno, null);
        }
        
        /// <remarks/>
        public void GenerarAnalisisCualitativoAsync(string idProceso, string idCliente, string fechaRevision, string usuario, string codError, string mensajeRetorno, object userState) {
            if ((this.GenerarAnalisisCualitativoOperationCompleted == null)) {
                this.GenerarAnalisisCualitativoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarAnalisisCualitativoOperationCompleted);
            }
            this.InvokeAsync("GenerarAnalisisCualitativo", new object[] {
                        idProceso,
                        idCliente,
                        fechaRevision,
                        usuario,
                        codError,
                        mensajeRetorno}, this.GenerarAnalisisCualitativoOperationCompleted, userState);
        }
        
        private void OnGenerarAnalisisCualitativoOperationCompleted(object arg) {
            if ((this.GenerarAnalisisCualitativoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarAnalisisCualitativoCompleted(this, new GenerarAnalisisCualitativoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarCalificacionSBS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerarCalificacionSBS(string idCliente, string idProceso, string usuario, ref string codError, ref string mensajeRetorno) {
            object[] results = this.Invoke("GenerarCalificacionSBS", new object[] {
                        idCliente,
                        idProceso,
                        usuario,
                        codError,
                        mensajeRetorno});
            codError = ((string)(results[0]));
            mensajeRetorno = ((string)(results[1]));
        }
        
        /// <remarks/>
        public void GenerarCalificacionSBSAsync(string idCliente, string idProceso, string usuario, string codError, string mensajeRetorno) {
            this.GenerarCalificacionSBSAsync(idCliente, idProceso, usuario, codError, mensajeRetorno, null);
        }
        
        /// <remarks/>
        public void GenerarCalificacionSBSAsync(string idCliente, string idProceso, string usuario, string codError, string mensajeRetorno, object userState) {
            if ((this.GenerarCalificacionSBSOperationCompleted == null)) {
                this.GenerarCalificacionSBSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarCalificacionSBSOperationCompleted);
            }
            this.InvokeAsync("GenerarCalificacionSBS", new object[] {
                        idCliente,
                        idProceso,
                        usuario,
                        codError,
                        mensajeRetorno}, this.GenerarCalificacionSBSOperationCompleted, userState);
        }
        
        private void OnGenerarCalificacionSBSOperationCompleted(object arg) {
            if ((this.GenerarCalificacionSBSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarCalificacionSBSCompleted(this, new GenerarCalificacionSBSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaHostGarantias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaHostGarantias(string numeroIdentificacion, string tipoIdentificacion, string idProceso, ref string CodError, ref string MensajeError) {
            object[] results = this.Invoke("ConsultaHostGarantias", new object[] {
                        numeroIdentificacion,
                        tipoIdentificacion,
                        idProceso,
                        CodError,
                        MensajeError});
            CodError = ((string)(results[1]));
            MensajeError = ((string)(results[2]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaHostGarantiasAsync(string numeroIdentificacion, string tipoIdentificacion, string idProceso, string CodError, string MensajeError) {
            this.ConsultaHostGarantiasAsync(numeroIdentificacion, tipoIdentificacion, idProceso, CodError, MensajeError, null);
        }
        
        /// <remarks/>
        public void ConsultaHostGarantiasAsync(string numeroIdentificacion, string tipoIdentificacion, string idProceso, string CodError, string MensajeError, object userState) {
            if ((this.ConsultaHostGarantiasOperationCompleted == null)) {
                this.ConsultaHostGarantiasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaHostGarantiasOperationCompleted);
            }
            this.InvokeAsync("ConsultaHostGarantias", new object[] {
                        numeroIdentificacion,
                        tipoIdentificacion,
                        idProceso,
                        CodError,
                        MensajeError}, this.ConsultaHostGarantiasOperationCompleted, userState);
        }
        
        private void OnConsultaHostGarantiasOperationCompleted(object arg) {
            if ((this.ConsultaHostGarantiasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaHostGarantiasCompleted(this, new ConsultaHostGarantiasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaMesesIva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaMesesIva(ref string CodError, ref string MensajeError) {
            object[] results = this.Invoke("ConsultaMesesIva", new object[] {
                        CodError,
                        MensajeError});
            CodError = ((string)(results[1]));
            MensajeError = ((string)(results[2]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaMesesIvaAsync(string CodError, string MensajeError) {
            this.ConsultaMesesIvaAsync(CodError, MensajeError, null);
        }
        
        /// <remarks/>
        public void ConsultaMesesIvaAsync(string CodError, string MensajeError, object userState) {
            if ((this.ConsultaMesesIvaOperationCompleted == null)) {
                this.ConsultaMesesIvaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaMesesIvaOperationCompleted);
            }
            this.InvokeAsync("ConsultaMesesIva", new object[] {
                        CodError,
                        MensajeError}, this.ConsultaMesesIvaOperationCompleted, userState);
        }
        
        private void OnConsultaMesesIvaOperationCompleted(object arg) {
            if ((this.ConsultaMesesIvaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaMesesIvaCompleted(this, new ConsultaMesesIvaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaHostRiesgos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ConsultaHostRiesgos(int idProceso, string tipoIDPer, string numIdentf, decimal riesgoPropuesto, ref string CodError, ref string MensajeError) {
            object[] results = this.Invoke("ConsultaHostRiesgos", new object[] {
                        idProceso,
                        tipoIDPer,
                        numIdentf,
                        riesgoPropuesto,
                        CodError,
                        MensajeError});
            CodError = ((string)(results[0]));
            MensajeError = ((string)(results[1]));
        }
        
        /// <remarks/>
        public void ConsultaHostRiesgosAsync(int idProceso, string tipoIDPer, string numIdentf, decimal riesgoPropuesto, string CodError, string MensajeError) {
            this.ConsultaHostRiesgosAsync(idProceso, tipoIDPer, numIdentf, riesgoPropuesto, CodError, MensajeError, null);
        }
        
        /// <remarks/>
        public void ConsultaHostRiesgosAsync(int idProceso, string tipoIDPer, string numIdentf, decimal riesgoPropuesto, string CodError, string MensajeError, object userState) {
            if ((this.ConsultaHostRiesgosOperationCompleted == null)) {
                this.ConsultaHostRiesgosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaHostRiesgosOperationCompleted);
            }
            this.InvokeAsync("ConsultaHostRiesgos", new object[] {
                        idProceso,
                        tipoIDPer,
                        numIdentf,
                        riesgoPropuesto,
                        CodError,
                        MensajeError}, this.ConsultaHostRiesgosOperationCompleted, userState);
        }
        
        private void OnConsultaHostRiesgosOperationCompleted(object arg) {
            if ((this.ConsultaHostRiesgosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaHostRiesgosCompleted(this, new ConsultaHostRiesgosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ConsultarPrecalificadorCompletedEventHandler(object sender, ConsultarPrecalificadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPrecalificadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPrecalificadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ProcesarPDFImpuestoRentaCompletedEventHandler(object sender, ProcesarPDFImpuestoRentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcesarPDFImpuestoRentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcesarPDFImpuestoRentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string codError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string mensajeRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ProcesarPDFDeclaracionIVACompletedEventHandler(object sender, ProcesarPDFDeclaracionIVACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcesarPDFDeclaracionIVACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcesarPDFDeclaracionIVACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string codError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string mensajeRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ProcesoDeclaracionIVACompletedEventHandler(object sender, ProcesoDeclaracionIVACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcesoDeclaracionIVACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcesoDeclaracionIVACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string codError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string mensajeRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ConsultaAnyosWebCompletedEventHandler(object sender, ConsultaAnyosWebCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaAnyosWebCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaAnyosWebCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Consultar_Ins_Updt_Clientes_Rating_NeoCompletedEventHandler(object sender, Consultar_Ins_Updt_Clientes_Rating_NeoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consultar_Ins_Updt_Clientes_Rating_NeoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consultar_Ins_Updt_Clientes_Rating_NeoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string CodError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string mensajeRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string IdClienteRating {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string IdProcesoRating {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string fechaRevision {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GenerarVariaciones_Indicadores_FlujoEfectivoCompletedEventHandler(object sender, GenerarVariaciones_Indicadores_FlujoEfectivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarVariaciones_Indicadores_FlujoEfectivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarVariaciones_Indicadores_FlujoEfectivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string codError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string mensajeRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GenerarAnalisisCualitativoCompletedEventHandler(object sender, GenerarAnalisisCualitativoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarAnalisisCualitativoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarAnalisisCualitativoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string codError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string mensajeRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GenerarCalificacionSBSCompletedEventHandler(object sender, GenerarCalificacionSBSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarCalificacionSBSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarCalificacionSBSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string codError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string mensajeRetorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ConsultaHostGarantiasCompletedEventHandler(object sender, ConsultaHostGarantiasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaHostGarantiasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaHostGarantiasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string CodError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ConsultaMesesIvaCompletedEventHandler(object sender, ConsultaMesesIvaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaMesesIvaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaMesesIvaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string CodError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ConsultaHostRiesgosCompletedEventHandler(object sender, ConsultaHostRiesgosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaHostRiesgosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaHostRiesgosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string CodError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591